### ISSUE TITLE
Generating openAPIV3Schema YAML file

### ISSUE THREAD

**Issue by aabouzaid** [kubernetes/kube-openapi#426]
Hi :wave: 

I'm looking for a tool to generate `openAPIV3Schema` YAML file like in `KRMFunctionDefinition` or `CustomResourceDefinition`.
I was able to generate the `openapi_generated.go` (GetOpenAPIDefinitions) using `openapi-gen` CLI tool.

However, it's not clear to me how to generate the actual KFD or CRD YAML out of that :thinking: 

I want to generate something like [this](https://github.com/aabouzaid/kustomize-kubeconformvalidator/blob/8f9abb86857d6bf59cbda65436ba185aa888f1dd/plugin-schema.yaml):

```
apiVersion: config.kubernetes.io/v1alpha1
kind: KRMFunctionDefinition
metadata:
  name: kubeconformvalidator
spec:
  group: validators.kustomize.aabouzaid.com
  names:
    kind: KubeconformValidator
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
                minLength: 1
            required:
            - name
          spec:
          [...]
```
