### ISSUE TITLE
Using kube-openapi + 'kubectl explain' on Custom Resources?

### ISSUE THREAD

**Issue by devdattakulkarni** [kubernetes/kube-openapi#97]
I was wondering if 'kubectl explain' can be used to find out information about Custom Resources?

Based on my understanding of kube-openapi and 'kubectl explain' workflow, it seems to me that this is currently not possible. Is this correct understanding?

I have written up my analysis here:
https://medium.com/@cloudark/understanding-kubectl-explain-9d703396cc8

Could you take a look and let me know if it is correct?

cc: @sttts

**Comment by sttts** [comment]
We don't publish the validation OpenAPI schema of CRD as part of the swagger.json. We should do that (with some loss in expressivity because we are still on OpenAPI v2 there, but on v3 for CRD validation). I am sure we also have an issue for that. This isn't too hard to do, just nobody did it.

**Comment by sttts** [comment]
I don't agree with the `kubectl get --raw /apis/kubediscovery.cloudark.io/v1/namespaces/default/Postgres/
explain` approach from the linked medium post. The OpenAPI spec published by the API server has to be updated dynamically in-memory with CRD validation schemata. This is possible and the whole apiserver architecture is build towards that.

**Comment by devdattakulkarni** [comment]
Thanks @sttts for the inputs.

I will be happy to contribute on this issue. Can you share the link to the issue
and any other relevant pointers?

**Comment by mingfang** [comment]
is there a plan for this?

**Comment by devdattakulkarni** [comment]
@mingfang I haven't heard anything on it yet.

I the mean while we have implemented the solution outlined in the blog post. 
If you are interested in checking it out, try the steps here:
https://github.com/cloud-ark/kubeplus/blob/master/kubeplus-steps.txt

OpenAPI Spec for Postgres custom resource can be queried as shown in line:
https://github.com/cloud-ark/kubeplus/blob/master/kubeplus-steps.txt#L47

**Comment by mingfang** [comment]
It looks like progress relating to this is being made in kubernetes v1.13.

**Comment by roycaihw** [comment]
kubernetes/kubernetes#67205 was moved out of 1.13 because we hit some snags. We opened https://github.com/kubernetes/kubernetes/pull/71192 to continue the development. It will address the `kubectl explain` CR issue.

**Comment by roycaihw** [comment]
the publish CRD openapi feature has been merged in 1.14 https://github.com/kubernetes/kubernetes/pull/71192

website documentation on how to enable the feature is to be merged in https://github.com/kubernetes/website/pull/12910

/close

**Comment by mingfang** [comment]
@roycaihw It looks like 1.14 does not fully address this issue.
Given this CRD 
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
  - name: v1
    served: true
    storage: true
  version: v1
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            cronSpec:
              type: string
              pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
            replicas:
              type: integer
              minimum: 1
              maximum: 10
```
kubectl explain only shows the metadata but not the spec.
```sh
kubectl explain crontabs --recursive
KIND:     CronTab
VERSION:  stable.example.com/v1

DESCRIPTION:
     <empty>

FIELDS:
   apiVersion	<string>
   kind	<string>
   metadata	<Object>
      annotations	<map[string]string>
      labels	<map[string]string>
      name	<string>
      namespace	<string>
      <removed non-relevant fields>
   spec	<>
```
I expected the spec to be filled in.
Using the openapi's visitor pattern, I'm getting called on VisitArbitrary() for the spec.
This call does not have any information about the spec, such as cronSpec in this case.

How does kubectl handle this?

**Comment by sttts** [comment]
You forgot to specify `type: object` for the spec. For backwards compatibility reasons we cannot publish `properties` "alone".

**Comment by mingfang** [comment]
@stts Thanks. I confirm that setting spec.type = object works.

**Comment by mingfang** [comment]
I ran a few tests with variations of the crontab CRD.
First is the basic CRD without any openAPIV3Schema, second is with openAPIV3Schema but not spec type(above) and finally with spec.type = object.

In all cases, the request sent by```kubectl create -f crontab.yaml --v=8``` where crontab is 
```
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image
```
is the same
```javascript
{"apiVersion":"stable.example.com/v1","kind":"CronTab",
"metadata":{"name":"my-new-cron-object","namespace":"default"},
"spec":{"cronSpec":"* * * * */5","image":"my-awesome-cron-image"}}
```

Can I assume from this that kubectl and api-server always expects the spec to be an object regardless of whether there is an openAPIV3Schema and spec.type?
and that the openAPIV3Schema only changes the published openapi?
